on:
  pull_request:
    paths: &paths
      - 'bin/**'
      - 'config/**'
      - 'resources/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

  push:
    branches: ['master']
    paths: *paths

name: build

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5

    steps:
      - name: Checkout.
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC', pcov.directory=$GITHUB_WORKSPACE, pcov.exclude=#^(?!($GITHUB_WORKSPACE/config/|$GITHUB_WORKSPACE/src/)).*#
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db and yiisoft/db-sqlite
        uses: yiisoft/actions/install-packages@master
        with:
          packages: >-
            ['db', 'db-sqlite']

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Migration --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        if: matrix.php == '8.5'
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
