on:
  pull_request:
    paths: &paths
      - 'resources/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/pgsql.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

  push:
    branches: ['master']
    paths: *paths

name: pgsql

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: yiisoft/actions/.github/workflows/db-pgsql.yml@master
