on:
  pull_request:
    paths:
      - 'bin/**'
      - 'src/**'
      - '.github/workflows/static.yml'
      - 'psalm*.xml'
      - 'composer.json'

  push:
    branches: ['master']
    paths:
      - 'bin/**'
      - 'src/**'
      - '.github/workflows/static.yml'
      - 'psalm*.xml'
      - 'composer.json'

name: static analysis

jobs:
  psalm:
    name: PHP ${{ matrix.php }}

    env:
      COMPOSER_ROOT_VERSION: dev-master
      extensions: pdo

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: cs2pr

      - name: Update composer.
        run: composer self-update

      - name: Set environment variables pull request linux.
        uses: yiisoft/actions/db/environment-linux@master

      - name: Install db.
        uses: yiisoft/actions/db/subpackage-install@master
        with:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          COMPOSER_ROOT_VERSION: ${{ env.COMPOSER_ROOT_VERSION }}
          CURRENT_PACKAGE: db
          FULL_BRANCH_NAME: ${{ env.FULL_BRANCH_NAME }}
          WORK_PACKAGE_URL: ${{ env.WORK_PACKAGE_URL }}

      - name: Static analysis.
        run: vendor/bin/psalm --config=${{ inputs.psalm-config }} --shepherd --stats --output-format=github --php-version=${{ matrix.php }}
