on:
  pull_request:
    paths:
      - 'bin/**'
      - 'src/**'
      - '.github/workflows/static.yml'
      - 'psalm*.xml'
      - 'composer.json'

  push:
    branches: ['master']
    paths:
      - 'bin/**'
      - 'src/**'
      - '.github/workflows/static.yml'
      - 'psalm*.xml'
      - 'composer.json'

name: static analysis

jobs:
  psalm:
    uses: yiisoft/actions/.github/workflows/psalm.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2', '8.3']
